# build environment
FROM node:22 as build
WORKDIR /app
COPY package*.json ./
COPY . .
RUN yarn install

ENV VITE_AUTH_CLIENT="23d8e04c-9362-4870-bda2-dade6f9d0ffb"
# ENV VITE_AUTHORITY="https://login.microsoftonline.com/........"
# ENV VITE_CONFIG_SCOPE="api://0708e202-b5ad-4d95-9735-a631c715d6a9/Read"
# ENV VITE_BASE_URL_MAIN="https://pcs-main-api-test.azurewebsites.net/api"
# ENV VITE_BASE_URL_COMP="https://backend-procosys-completion-api-test.radix.equinor.com"
# ENV VITE_CONFIG_ENDPOINT="https://pcs-config-non-prod-func.azurewebsites.net/api/Frontend/Configuration?"
# ENV VITE_WEBAPI_SCOPE="api://2d0ed80f-3013-422d-b8bd-2b8ac70b2ce1/web_api"
# ENV VITE_COMP_SCOPE="api://cf2e4cc0-39fe-4604-ad64-98e392987821/ReadWrite"
# ENV VITE_APP_INSIGHTS="fcf22f65-a717-421f-935d-4853dbcbe8e5"
# ENV VITE_API_VERSION="&api-version=4.1"
# ENV VITE_OCR_ENDPOINT="https://pcs-mc-webapp-non-prod-funcs.azurewebsites.net/api/pcs_ocr?"

RUN yarn build --mode=production


# production environment
FROM docker.io/nginxinc/nginx-unprivileged:alpine

WORKDIR /app
## add permissions for nginx user
COPY --from=build /app/dist /usr/share/nginx/html/frontend
COPY .docker/nginx/ /etc/nginx/
COPY .docker/scripts/ /etc/scripts/
 
# Change the user from root to non-root- From now on, all Docker commands are run as non-root user (except for COPY)
USER 0
RUN chown -R nginx /usr/share/nginx/html/frontend \
    && chown -R nginx /etc/nginx/conf.d
USER 9999

EXPOSE 5000

CMD ["sh","/etc/scripts/startup.sh"]