# build environment
FROM node:20 as build
WORKDIR /app
COPY . .
RUN npm i -g pnpm@9.0.5
RUN pnpm install

ENV VITE_AUTH_CLIENT="30a25122-c22c-4a5c-a7b8-366d31cb2c46"
ENV VITE_CONFIG_SCOPE="api://756f2a23-f54d-4643-bb49-62c0db4802ae/Read"
ENV VITE_BASE_URL_MAIN="https://pcs-main-api-dev-pr.azurewebsites.net/api"
ENV VITE_CONFIG_ENDPOINT="https://pcs-config-non-prod-func.azurewebsites.net/api/Frontend/Configuration?"
ENV VITE_WEBAPI_SCOPE="api://47641c40-0135-459b-8ab4-459e68dc8d08/web_api"
ENV VITE_APP_INSIGHTS="cdb49dda-63f9-433d-99f3-c73dff5dc6a1"
ENV VITE_API_VERSION="&api-version=4.1"

RUN pnpm bundle

# production environment
FROM docker.io/nginxinc/nginx-unprivileged:alpine

WORKDIR /app

COPY --from=build /app/dist /usr/share/nginx/html
COPY .docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY .docker/scripts/ /etc/scripts/
 
USER 101
EXPOSE 5000

CMD ["sh","/etc/scripts/startup.sh"]
