apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-js-frontend
spec: 
  environments:
  - name: dev
  - name: test
  - name: prod

spec:
  environments:
  - name: dev
    build:
      from: develop
  - name: test
    build:
      from: test
  - name: prod
    build:
      from: master
  components:
  - name: frontend
    publicPort: http
    ports:
    - name: http
      port: 5000
    environmentConfig:
    - environment: dev
      dockerfileName: Dockerfile.dev
      variables:
        authSettingsEndpoint: 'https://pcs-config-non-prod-func.azurewebsites.net/api/Frontend/Auth'
    - environment: test
      dockerfileName: Dockerfile.test
      variables:
        authSettingsEndpoint: 'https://pcs-config-non-prod-func.azurewebsites.net/api/Frontend/Auth'
    - environment: prod
      dockerfileName: Dockerfile.prod
      variables:
        authSettingsEndpoint: 'https://pcs-config-prod-func.azurewebsites.net/api/Frontend/Auth'