apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-frontend
spec:
  dnsExternalAlias:
    - alias: procosystest.equinor.com
      component: frontend
      environment: test
      useCertificateAutomation: true
    - alias: procosys.equinor.com
      component: frontend
      environment: prod
      useCertificateAutomation: true
  environments:
  - name: dev
    build:
      from: develop
  - name: test
    build:
      from: feat/auth-silent
  - name: prod
    build:
      from: master
  components:
  - name: frontend
    variables:
      AUTH_CONFIG: ""
      CONFIGURATION: ""
      FEATURE_FLAGS: ""

    publicPort: http
    ports:
    - name: http
      port: 5000
    environmentConfig:
    - environment: dev
    - environment: test
    - environment: prod
