apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-frontend
spec:
  dnsExternalAlias:
    - alias: procosystest.equinor.com
      component: frontend
      environment: test
      useCertificateAutomation: true
    - alias: procosys.equinor.com
      component: frontend
      environment: prod
      useCertificateAutomation: true
  environments:
  - name: dev
    build:
      from: '*'

  - name: test
    build:
      from: '*'

  - name: prod
    build:
      from: master

  components:
  - name: frontend
    publicPort: http
    variables:
      ENDPOINT: "https://pcs-config-prod-func.azurewebsites.net/api/Frontend"
      SCOPE: "api://756f2a23-f54d-4643-bb49-62c0db4802ae/Read"

    ports:
    - name: http
      port: 5000
    environmentConfig:
    - environment: dev
    - environment: test
    - environment: prod
