trigger:
  branches:
    include:
      - pipeline-build

resources:
- repo: self

variables:
  System.Debug: 'true'
  vmImageName: 'ubuntu-latest'
  imageName: 'frontend'
  dockerRegistryServiceConnection: 'ACR - pcspreservation'
  containerRegistry: 'pcspreservation.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: pcs/pres/dev/$(imageName)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)
