# build environment
FROM node:12.12-alpine as build
WORKDIR /app
COPY . /app
RUN yarn install
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn build --mode=production

# production environment
FROM nginx:1.16.1-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY .docker/nginx/* /etc/nginx/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
